### PR TITLE
Update File Naming Conventions

### PR DESCRIPTION
**Pull request by kmgdevelopment**
- Change "lang.boo.php" to "boo_lang.php"
- Remove Blogger API file (add-on depreciated)

### CODE REVIEW

**Comment by kevinsmith** [comment]
Thanks for helping out here, Kristen. Looks like there are indeed some language keys that have yet to be translated into Spanish. I know you can get a good look at them by using the Translation Utility to [update the translation](http://ellislab.com/expressionengine/user-guide/cp/tools/utilities/translation_utility.html#updating-translations). Are you able to translate the English to Spanish yourself?

**Comment by kmgdevelopment** [comment]
Hi Kevin,

I'm afraid I'm not a Spanish speaker myself, so I wouldn't be qualified to update the pack.

**Comment by kevinsmith** [comment]
No worries, I can still complete the pull request. As far as you know, the only remaining issues are simply that some of the keys still lack a translation?

**Comment by kmgdevelopment** [comment]
Yeah, that's what it looks like to me.

**Comment by kevinsmith** [comment]
Awesome, thanks for your help Kristen! I'll merge this in, and hopefully a Spanish-speaker will help fill in the gaps.

**Pull request merged**
